                      


from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "docs" / "SHA256SUMS"
RELEASE_ROOT = ROOT / "releases" / "native"
GLOBS = ("*.exe", "*.zip", "*.tar.gz", "*.dmg", "*.deb", "*.rpm", "datascythe")


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def collect_artifacts() -> list[Path]:
    artifacts: list[Path] = []
    if not RELEASE_ROOT.exists():
        return artifacts
    for platform_dir in RELEASE_ROOT.iterdir():
        if not platform_dir.is_dir():
            continue
        for pattern in GLOBS:
            artifacts.extend(path for path in sorted(platform_dir.glob(pattern))
                             if not path.name.startswith("._"))
        for child in platform_dir.rglob("*"):
            if child.is_file() and child.name == "datascythe" and not child.name.startswith("._"):
                artifacts.append(child)
    return sorted({path.resolve() for path in artifacts})


def write_manifest(artifacts: list[Path]) -> None:
    lines = [
        f"# DataScythe release hash manifest",
        "# Generated by scripts/generate_sha256sums.py",
    ]
    for path in artifacts:
        rel = path.relative_to(ROOT).as_posix()
        lines.append(f"{sha256_file(path)}  {rel}")
    MANIFEST.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {MANIFEST} ({len(artifacts)} artifact(s))")


def validate_manifest() -> int:
    if not MANIFEST.exists():
        raise SystemExit(f"Missing manifest: {MANIFEST}")
    failures = 0
    for line in MANIFEST.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        digest, rel = line.split(maxsplit=1)
        path = ROOT / rel
        if not path.exists():
            print(f"MISSING: {rel}")
            failures += 1
            continue
        actual = sha256_file(path)
        if actual != digest:
            print(f"MISMATCH: {rel}")
            failures += 1
        else:
            print(f"OK: {rel}")
    return failures


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Validate existing manifest")
    args = parser.parse_args()

    if args.check:
        failures = validate_manifest()
        if failures:
            raise SystemExit(f"SHA256 validation failed ({failures} issue(s))")
        print("SHA256 validation passed.")
        return 0

    artifacts = collect_artifacts()
    if not artifacts:
        print("No release artifacts found under releases/native/.")
        return 0
    write_manifest(artifacts)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
